config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'sign_up', to: "users/registrations#new"
  end
  resources :users, only: [:show, :edit, :update, :destroy]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/guest_admin_sign_in', to: 'users/sessions#guest_admin_sign_in'
  end

  resources :tasks do
    resources :comments
  end
  resources :tasks do
    collection do
      get 'search'
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskxtap</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav_ver">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Task×Tap</a>
          </div>
          <div class="collapse navbar-collapse" id="nav_ver">
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to "マイページ", "/users/#{current_user.id}" %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                <% if current_user.try(:admin?) %>
                  <li><%= link_to "管理者専用", rails_admin_path %></li>
                <% end %>
              <% else %>
                <li><%= link_to "新規登録", new_user_registration_path %></li>
                <li><%= link_to "ログイン", new_user_session_path %></li>
                <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %></li>
                <li><%= link_to '管理者ゲストログイン（確認用）', users_guest_admin_sign_in_path, method: :post %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="main">
      <div class="alert-space">
        <% if notice %>
          <p class="alert alert-notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-error"><%= alert %></p>
        <% end %>
      </div>
      <%= yield %>
    </div>

    <footer>
      <p>©Task × Tap 2021 Copyright</p>
    </footer>
  </body>
</html>